### ISSUE TITLE
Handle projects without assets

### ISSUE THREAD

**Issue by ComLock** [enonic/starter-webpack#11]
Trying to convert the app into a lib gives errors about missing main.es6

ERROR in Entry module not found: Error: Can't resolve './js/main.es6' in '/Users/cwe/code/github/enonic/lib-url/src/main/resources/assets'

ERROR in Entry module not found: Error: Can't resolve './ts/main.ts' in '/Users/cwe/code/github/enonic/lib-url/src/main/resources/assets'

**Comment by ComLock** [comment]
As in: Handle projects without a main file

**Comment by ComLock** [comment]
Actually those errors are about asset files so I guess: Handle projects without assets.

**Comment by alansemenov** [comment]
The Starter is not supposed to handle all possible scenarios and we don't know what kind of project structure the user will want... It's _pre_configured to process sample .ts, .es6 etc files that we included in the project. If you wish to remove them for your project (and in most the cases you will) then you just change `context`, `output` and `entry` properties in the config file (`webpack.client.config.js` and `webpack.server.config.js`) according to your project structure. This is also described in the [Starter docs](https://developer.enonic.com/templates/webpack#project_structure)
