### ISSUE TITLE
@babel/plugin-proposal-class-properties

### ISSUE THREAD

**Issue by ComLock** [enonic/starter-webpack#12]
Please add @babel/plugin-proposal-class-properties to support class properties.

Or document a way to add your own babel plugins.

**Comment by ComLock** [comment]
I was able to add it in my project here:
https://github.com/enonic/starter-webpack/blob/730b3ee3f259b2be8d1586b7af04af3756c18e4b/webpack.server.config.js#L102

**Comment by alansemenov** [comment]
Yes, you can add whatever plugins you want, as described [here ](https://developer.enonic.com/templates/webpack#project_bundling). We want to avoid adding plugins that are not absolutely necessary for the Starter to function.

**Comment by ComLock** [comment]
No, those are webpack plugins, I'm talking about babel plugins...
