### ISSUE TITLE
Can't get build of this starter to work on Windows with XP7.2

### ISSUE THREAD

**Issue by Bellfalasch** [enonic/starter-webpack#14]
I'm assuming there's something wrong with the webpack config. But when we clone this repo and then run `./gradlew deploy` or `./gradlew deploy -Penv=dev` it will build the jar but all `require` within the build-folder gets a lot of `//` in their paths, they also keep their pre-babel file extensions, like `.ts` or `.es6` instead of poiting to the transpiled `.js` version.

This is a problem we have on Windows. My coworker on Mac had no problems. We're assuming we can build and try the starter without any prior configuration (can't find any hints to that in the adoc guide).

Error message given after installation locally, comes from Application Admin Tool:

> Resource [com.acme.example.webpack:/webapp/webapp\webapp.ts] was not found

 If I inspect the `/build` dir I will find `webapp/webapp.js`, no `.ts` (but that's expected), but still, the require statement inside this file is wrong, it points to the ts-file (with double back-slashes).

Could I get some help figuring out if this is a problem with this starter, on Windows? I'm not using the CLI for this, using only the included Gradle wrapper.

**Comment by alansemenov** [comment]
@Bellfalasch Hey Bobs, did you get this solved by [this fix](https://github.com/enonic/starter-webpack/commit/e93bfcdc2a0a2b936b6f17d493ff805c9d41fc5c)?

**Comment by Bellfalasch** [comment]
Sadly not. That double `external` thing tried to compile too many libraries (Enonic's own too) which broke the build. After that fix it works on Mac, still not on PC (but unrelated to this error here). However, even if this is still an issue I'm moving back to Mac and won't need a fix here, or be able to try something else out.
