### ISSUE TITLE
Replace deprecated css-mqpacker plugin

### ISSUE THREAD

**Issue by alansemenov** [enonic/starter-webpack#2]
[This plugin](https://www.npmjs.com/package/css-mqpacker) is deprecated but there's no alternative at the moment. 

[The fork is coming ](https://github.com/simbo/css-mqpacker-sort-mediaqueries/issues/1#issuecomment-482150079), so replace the plugin whenever the new alternative is available.

**Comment by sigdestad** [comment]
How is css-mqpacker relevant for building a webpack starter?

**Comment by alansemenov** [comment]
It's one of the webpack plugins used for processing stylesheets.

**Comment by sigdestad** [comment]
So, noone can use webpack these days?

**Comment by alansemenov** [comment]
I don't understand the question. How deprecation of one of the thousands of plugins can make no one use the webpack? Nashorn is deprecated but people are still using Java.

**Comment by sigdestad** [comment]
I'm saying, why is this blocking us from making a starter-webpack?

**Comment by alansemenov** [comment]
It's not of course - it's an issue I created in the backlog to not forget about it :)

**Comment by alansemenov** [comment]
Removed from the starter
