### ISSUE TITLE
Incorrect url in CLI(?)

### ISSUE THREAD

**Issue by Slideshow776** [enonic/starter-webpack#3]
When the CLI asks you if you would like to open the docs in a browser the resulting page is a 404.

![image](https://user-images.githubusercontent.com/4059636/58535323-f76f2780-81ed-11e9-9af7-05434e2195a9.png)

![image](https://user-images.githubusercontent.com/4059636/58535382-25546c00-81ee-11e9-8d33-6fa9ec60cd58.png)

**Comment by alansemenov** [comment]
Nice catch! Fixed
