### ISSUE TITLE
Webjars fail with Gradle 7

### ISSUE THREAD

**Issue by tajakobsen** [enonic/starter-webpack#318]
## How to recreate:

Add a webjar to dependencies in build.gradle

```groovy
dependencies {
  // ...
  webjar "org.webjars:bootstrap:5.1.3"
}
```

Build fails with the following message:

```
> Task :unpackWebJars FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':unpackWebJars'.
> Entry META-INF/MANIFEST.MF is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.3.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```

**Comment by alansemenov** [comment]
@tajakobsen if it's specifically about Bootstrap webjar, then this issue was solved [here](https://github.com/enonic/starter-bootstrap3/blob/master/build.gradle#L26) (a different id of the bootstrap webjar).

**Comment by tajakobsen** [comment]
@alansemenov From the error message – It appears that this issue can also be fixed by setting [`duplicatesStrategy` (which is supported by Gradle 6.8.3 too)](https://docs.gradle.org/6.8.3/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy).

Could it be prudent to set `duplicatesStrategy` in [UnpackWebJarTask in xp-gradle-plugin](https://github.com/enonic/xp-gradle-plugin/blob/6f2f7cc5d736e0f9a1c63dfa3d49b8eb14498c42/src/main/java/com/enonic/gradle/xp/app/UnpackWebJarTask.java#L38) (which is on gradle 6.8.3).

We don't know if other webjars has this issue too.

**Comment by alansemenov** [comment]
Should be solved in the Gradle plugin now
