### ISSUE TITLE
Output from TypeScript compilation depends on ts-files

### ISSUE THREAD

**Issue by tajakobsen** [enonic/starter-webpack#37]
Building a project containing ts-files works, but the outputted js-files contains references to the original ts-files, and this crashes the page when deployed.

To see this behavior, just try to build a fresh project based on the "webpack starter". You can go to the file: */build/resources/main/webapp/webapp.js*, and see the following at the end of the file.

```
e.exports=require("./webapp/webapp.ts")
```

For some reason it doesn't compile the ts-file, it just creates a js-file that references it.

**Comment by alansemenov** [comment]
![image](https://user-images.githubusercontent.com/11612490/91564244-a2feae80-e940-11ea-9028-f50d5387fd27.png)

**Comment by edloidas** [comment]
Latest versions of the terser plugin that is used in this starter for optimization removes the `console.*` calls, when the default config is used. Custom config will do the trick. This should be fixed in the [latest commit](2349e88e560bb9957342784beb86232783aec431).
