### ISSUE TITLE
Transpile and bundle serverside code

### ISSUE THREAD

**Issue by ComLock** [enonic/starter-webpack#4]
Transpile ecmascript and typescript to javascript.
Bundle node_modules.
Keep Enonic XP libs as externals.

Support a bunch of common file extentions?

**Comment by alansemenov** [comment]
> Transpile ecmascript and typescript to javascript.

Yes.

> Bundle node_modules.

Mmm.... Not necessary, should be optional. I think we will describe this in the [starter docs](https://developer.enonic.com/starters/starter-webpack), @mta. "_If you want to import an external NPM module, it has to be bundled together with the app assets, like this: ..._" 

> Keep Enonic XP libs as externals.

Not sure what this means? They are bundled in the jar if the app has dependencies to them.

> Support a bunch of common file extentions?

We cannot support all of them. Again, we need to describe this in the docs. @mta, let's add a separate section on the webpack.config.js where we describe how to expanded supported extensions.

**Comment by ComLock** [comment]
Webpack will fail if it discovers an import it can't find. To avoid this one can configure externals. Typically I configure a regular expression such that any import that starts with a slash is an external library.

If you use relative paths webpack will bundle the imported functions.
If you use absolute paths webpack will not bundle and resolving the imports happens runtime.

**Comment by ComLock** [comment]
The "problem" with using externals is that if you reference a library that's not present in the jar you will get a runtime error.

You can write your own webpack resolver plugin, so it should be possible to look inside the jar files and give a build time resolve error.
