### ISSUE TITLE
Bundle Ecmascript module assets

### ISSUE THREAD

**Issue by ComLock** [enonic/starter-webpack#5]
Using EsmWebpackPlugin.
See https://github.com/enonic/lib-explorer/blob/master/webpack.config.babel.js#L388

**Comment by alansemenov** [comment]
Interesting proposal but we won't do it in **this** starter. We have to keep it as clean and simple as possible, as in support basic operations one needs in a webapp/site - SASS/LESS -> CSS and ES -> JS. We'll add Typescript support but that's already an edge case.

Bundling app as a lib is a very special corner case (just look at the number of weekly downloads). Those who want it will simply add the plugin after the project is created. What we could do though is implement this in our [Lib starter](https://github.com/enonic/starter-lib), where it belongs much better.

**Comment by alansemenov** [comment]
Added an issue here: https://github.com/enonic/starter-lib/issues/4
